<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobPostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobPostsRepository extends EntityRepository
{
}
