login:
    pattern:              /login
    defaults:             { _controller: MySecurityBundle:Security:login }
    requirements:
        _method:            GET

login_check:
    pattern:              /login_check

logout:
    pattern:              /logout
